### ISSUE TITLE
Create a list of entities which are requested from CS and needed for vault project

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-entities#1]

**Comment by MedvedevBW** [comment]
1. Analyze the requirements for Vault project
2. Сompare it with CloudStack entities in "cs-vault-server" project
3. Create list of entities

**Comment by MedvedevBW** [comment]
This is entities list: https://docs.google.com/a/bw-sw.com/document/d/1W1f8WlRZoWvfx6RGkSkgBLb7N4OiS7x38LfnC8QozJY/edit?usp=sharing
