### ISSUE TITLE
Add code coverage into Jenkins job and set up reporting into Jenkins

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-entities#12]
Change in code coverage should not fail build.
The step should be after code style pass.

**Comment by MedvedevBW** [comment]
@Krisilda Can we use Jenkins report instead of GitHub report again?

**Comment by Krisilda** [comment]
@MedvedevBW yes. I  have changed task name.

**Comment by MedvedevBW** [comment]
Implement in #17
