### ISSUE TITLE
Write documentation (readme)

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-entities#27]

**Comment by placccebo** [comment]
# cs-entities
Simple CloudStack Entities Framework

## Install with SBT

Add the following to your `build.sbt`
```scala
libraryDependencies += "com.bwsw" %% "cs-entities" % "4.9.3"
```
## Getting Started

## Example Usage

## Testing

### Unit tests

Run tests: `sbt test`

### Integration tests


## Versioning

Library has the same version as Apache CloudStack

## License

This project is licensed under the Apache License - see the [LICENSE](LICENSE) file for details
