### ISSUE TITLE
Update documentation according to changes in #25

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-entities#43]
Class diagram. 
Sequence diagram.

**Comment by MedvedevBW** [comment]
class diagram https://drive.google.com/open?id=17FcVyk9OshBF2Q6JW6ukAZ_rObdk22w4
sequence diagram https://drive.google.com/open?id=1xlCLYnW-vipPH_ptw4VjMKOcjturVB9V
user implementation class diagram https://drive.google.com/open?id=1QGWF5HwzOUgfWqGXzDnq7bJlaaxeHctX
