### ISSUE TITLE
Add necessary fields to entities from the list for both projects 

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-entities#6]

**Comment by MedvedevBW** [comment]
1. Identify common parameters for "create" and "read" requests for "accounting service" project
   a. Analyze the resources for accounting and create list of events for it.
   b. Analyze the list of events and identify the information which not include to events, but necessary for     accounting.
2. Combine it with entities for "cs-vault-server" project (entities for "cs-vault-server" was described in #1)
